In [3]:
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd().parent
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "twcs.csv"

print("Dataset path:")
print(DATA_PATH)

Dataset path:
c:\Users\arnav\OneDrive\Desktop\hiver-ai-support-agent\data\raw\twcs.csv

In [4]:
df_sample = pd.read_csv(
    DATA_PATH,
    nrows=100_000
)

print("Sample shape:", df_sample.shape)

Sample shape: (100000, 7)

In [5]:
print("Columns:")
for column in df_sample.columns:
    print("-", column)

Columns:
- tweet_id
- author_id
- inbound
- created_at
- text
- response_tweet_id
- in_response_to_tweet_id

In [6]:
df_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   tweet_id                 100000 non-null  int64
 1   author_id                100000 non-null  str
 2   inbound                  100000 non-null  bool
 3   created_at               100000 non-null  str
 4   text                     100000 non-null  str
 5   response_tweet_id        67571 non-null   str
 6   in_response_to_tweet_id  74090 non-null   float64
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 20.3 MB

In [7]:
df_sample.describe()

            tweet_id  in_response_to_tweet_id
count  100000.000000             74090.000000
mean    63430.983200             63062.375422
std     36612.198664             36551.446104
min         1.000000                 1.000000
25%     31494.750000             31049.250000
50%     61711.500000             61440.000000
75%     96484.250000             95919.500000
max    126124.000000            126125.000000

In [8]:
df_sample[[
    "tweet_id",
    "author_id",
    "inbound",
    "text",
    "response_tweet_id",
    "in_response_to_tweet_id"
]].head(10)

,tweet_id,author_id,inbound,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,@sprintcare I did.,4,6.0
5,6,sprintcare,False,@115712 Can you please send us a private messa...,"5,7",8.0
6,8,115712,True,@sprintcare is the worst customer service,"9,6,10",NaN
7,11,sprintcare,False,@115713 This is saddening to hear. Please shoo...,NaN,12.0
8,12,115713,True,@sprintcare You gonna magically change your co...,"11,13,14",15.0
9,15,sprintcare,False,@115713 We understand your concerns and we'd l...,12,16.0

In [9]:
missing = pd.DataFrame({
    "missing_count": df_sample.isna().sum(),
    "missing_percentage": (
        df_sample.isna().mean() * 100
    ).round(2)
})

missing

                         missing_count  missing_percentage
tweet_id                             0                0.00
author_id                            0                0.00
inbound                              0                0.00
created_at                           0                0.00
text                                 0                0.00
response_tweet_id                32429               32.43
in_response_to_tweet_id          25910               25.91

In [10]:
print("Inbound distribution:")
print(df_sample["inbound"].value_counts())

print("\nPercentage:")
print(
    (df_sample["inbound"].value_counts(normalize=True) * 100)
    .round(2)
)

Inbound distribution:
inbound
True     54948
False    45052
Name: count, dtype: int64

Percentage:
inbound
True     54.95
False    45.05
Name: proportion, dtype: float64

In [11]:
print(
    "Unique author IDs:",
    df_sample["author_id"].nunique()
)

Unique author IDs: 27592

In [12]:
author_counts = (
    df_sample["author_id"]
    .value_counts()
    .head(30)
)

author_counts

author_id
AmazonHelp         6924
AppleSupport       3106
Uber_Support       2102
Tesco              1450
SpotifyCares       1356
British_Airways    1156
comcastcares       1092
sainsburys         1081
Delta              1039
VirginTrains       1001
AmericanAir         956
ChipotleTweets      889
O2                  843
GWRHelp             826
hulu_support        823
XboxSupport         816
TMobileHelp         816
SouthwestAir        793
Ask_Spectrum        763
idea_cares          743
ArgosHelpers        697
AirAsiaSupport      658
sprintcare          646
UPSHelp             632
VerizonSupport      631
MicrosoftHelps      622
AskPlayStation      621
Safaricom_Care      591
ATVIAssist          550
SW_Help             532
Name: count, dtype: int64

In [13]:
company_tweets = df_sample[
    df_sample["inbound"] == False
].copy()

print(
    "Company-side tweets:",
    len(company_tweets)
)

print(
    "Company-side accounts:",
    company_tweets["author_id"].nunique()
)

Company-side tweets: 45052
Company-side accounts: 105

In [14]:
company_activity = (
    company_tweets["author_id"]
    .value_counts()
    .rename("company_replies")
)

company_activity.head(30)

author_id
AmazonHelp         6924
AppleSupport       3106
Uber_Support       2102
Tesco              1450
SpotifyCares       1356
British_Airways    1156
comcastcares       1092
sainsburys         1081
Delta              1039
VirginTrains       1001
AmericanAir         956
ChipotleTweets      889
O2                  843
GWRHelp             826
hulu_support        823
XboxSupport         816
TMobileHelp         816
SouthwestAir        793
Ask_Spectrum        763
idea_cares          743
ArgosHelpers        697
AirAsiaSupport      658
sprintcare          646
UPSHelp             632
VerizonSupport      631
MicrosoftHelps      622
AskPlayStation      621
Safaricom_Care      591
ATVIAssist          550
SW_Help             532
Name: company_replies, dtype: int64

In [15]:
customer_tweets = df_sample[
    df_sample["inbound"] == True
].copy()

customer_activity = (
    customer_tweets["author_id"]
    .value_counts()
    .rename("customer_tweets")
)

customer_activity.head(30)

author_id
117242    56
116230    42
115911    39
117627    39
115888    38
123287    38
122277    33
134104    33
142385    31
119439    30
120261    30
126781    30
131812    29
133542    29
130654    27
132028    27
115714    25
120648    25
131820    25
143890    25
132727    24
117624    23
118505    23
120576    23
123963    23
131476    23
117721    22
118392    22
119703    22
120701    22
Name: customer_tweets, dtype: int64

In [16]:
candidate_analysis = pd.concat(
    [
        company_activity,
        customer_activity
    ],
    axis=1
).fillna(0)

candidate_analysis["total_activity"] = (
    candidate_analysis["company_replies"]
    + candidate_analysis["customer_tweets"]
)

candidate_analysis = candidate_analysis.sort_values(
    "company_replies",
    ascending=False
)

candidate_analysis.head(30)

                 company_replies  customer_tweets  total_activity
author_id
AmazonHelp                6924.0              0.0          6924.0
AppleSupport              3106.0              0.0          3106.0
Uber_Support              2102.0              0.0          2102.0
Tesco                     1450.0              0.0          1450.0
SpotifyCares              1356.0              0.0          1356.0
British_Airways           1156.0              0.0          1156.0
comcastcares              1092.0              0.0          1092.0
sainsburys                1081.0              0.0          1081.0
Delta                     1039.0              0.0          1039.0
VirginTrains              1001.0              0.0          1001.0
AmericanAir                956.0              0.0           956.0
ChipotleTweets             889.0              0.0           889.0
O2                         843.0              0.0           843.0
GWRHelp                    826.0              0.0           826.0
hulu_support               823.0              0.0           823.0
XboxSupport                816.0              0.0           816.0
TMobileHelp                816.0              0.0           816.0
SouthwestAir               793.0              0.0           793.0
Ask_Spectrum               763.0              0.0           763.0
idea_cares                 743.0              0.0           743.0
ArgosHelpers               697.0              0.0           697.0
AirAsiaSupport             658.0              0.0           658.0
sprintcare                 646.0              0.0           646.0
UPSHelp                    632.0              0.0           632.0
VerizonSupport             631.0              0.0           631.0
MicrosoftHelps             622.0              0.0           622.0
AskPlayStation             621.0              0.0           621.0
Safaricom_Care             591.0              0.0           591.0
ATVIAssist                 550.0              0.0           550.0
SW_Help                    532.0              0.0           532.0

In [17]:
candidate_analysis = pd.concat(
    [
        company_activity,
        customer_activity
    ],
    axis=1
).fillna(0)

candidate_analysis["total_activity"] = (
    candidate_analysis["company_replies"]
    + candidate_analysis["customer_tweets"]
)

candidate_analysis = candidate_analysis.sort_values(
    "company_replies",
    ascending=False
)

candidate_analysis.head(30)

                 company_replies  customer_tweets  total_activity
author_id
AmazonHelp                6924.0              0.0          6924.0
AppleSupport              3106.0              0.0          3106.0
Uber_Support              2102.0              0.0          2102.0
Tesco                     1450.0              0.0          1450.0
SpotifyCares              1356.0              0.0          1356.0
British_Airways           1156.0              0.0          1156.0
comcastcares              1092.0              0.0          1092.0
sainsburys                1081.0              0.0          1081.0
Delta                     1039.0              0.0          1039.0
VirginTrains              1001.0              0.0          1001.0
AmericanAir                956.0              0.0           956.0
ChipotleTweets             889.0              0.0           889.0
O2                         843.0              0.0           843.0
GWRHelp                    826.0              0.0           826.0
hulu_support               823.0              0.0           823.0
XboxSupport                816.0              0.0           816.0
TMobileHelp                816.0              0.0           816.0
SouthwestAir               793.0              0.0           793.0
Ask_Spectrum               763.0              0.0           763.0
idea_cares                 743.0              0.0           743.0
ArgosHelpers               697.0              0.0           697.0
AirAsiaSupport             658.0              0.0           658.0
sprintcare                 646.0              0.0           646.0
UPSHelp                    632.0              0.0           632.0
VerizonSupport             631.0              0.0           631.0
MicrosoftHelps             622.0              0.0           622.0
AskPlayStation             621.0              0.0           621.0
Safaricom_Care             591.0              0.0           591.0
ATVIAssist                 550.0              0.0           550.0
SW_Help                    532.0              0.0           532.0

In [18]:
# Investigate 

brand_name = "AmazonHelp"

amazon_tweets = df_sample[
    df_sample["author_id"] == brand_name
].copy()

print("AmazonHelp tweets:", len(amazon_tweets))

print("\nInbound distribution:")
print(amazon_tweets["inbound"].value_counts())

print("\nSample AmazonHelp replies:")
print(
    amazon_tweets[
        ["tweet_id", "text", "in_response_to_tweet_id", "response_tweet_id"]
    ].head(10).to_string(index=False)
)

AmazonHelp tweets: 6924

Inbound distribution:
inbound
False    6924
Name: count, dtype: int64

Sample AmazonHelp replies:
 tweet_id                                                                                                                                                      text  in_response_to_tweet_id response_tweet_id
      269                            @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET                    272.0           270,271
      273                                                                                     @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET                    271.0               274
      275                                                                                                    @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET                    274.0               NaN
      324 @115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET                    325.0               NaN
      615                     @115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN                    617.0               616
      618                           @115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG                    616.0               619
      620                   @115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH                    621.0               NaN
      622                            @115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS                    624.0               623
      625                                                                                                      @115824 Wir haben zu danken. Schönen Abend noch. ^JS                    623.0               NaN
      626                                                @115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ                    628.0               627

In [19]:


amazon_reply_ids = set(
    amazon_tweets["in_response_to_tweet_id"]
    .dropna()
    .astype(str)
)

customer_messages = df_sample[
    df_sample["tweet_id"].astype(str).isin(amazon_reply_ids)
].copy()

print("Customer messages with AmazonHelp replies:",
      len(customer_messages))

customer_messages[
    ["tweet_id", "text", "in_response_to_tweet_id"]
].head(20)

Customer messages with AmazonHelp replies: 0

Empty DataFrame
Columns: [tweet_id, text, in_response_to_tweet_id]
Index: []

In [20]:
conversation_examples = amazon_tweets.merge(
    customer_messages[
        ["tweet_id", "text"]
    ],
    left_on="in_response_to_tweet_id",
    right_on="tweet_id",
    how="inner",
    suffixes=("_brand", "_customer")
)

print("Matched conversations:",
      len(conversation_examples))

conversation_examples[
    ["text_customer", "text_brand"]
].head(20)

Matched conversations: 0

Empty DataFrame
Columns: [text_customer, text_brand]
Index: []

In [21]:
coverage = len(conversation_examples) / len(amazon_tweets)

print(f"AmazonHelp reply-to-customer coverage: {coverage:.2%}")

AmazonHelp reply-to-customer coverage: 0.00%

In [22]:
for i, row in conversation_examples.head(5).iterrows():
    print("=" * 80)
    print("CUSTOMER:")
    print(row["text_customer"])
    print("\nAMAZONHELP:")
    print(row["text_brand"])

In [23]:
def analyze_brand(brand_name, df):
    brand_tweets = df[
        df["author_id"] == brand_name
    ].copy()

    reply_ids = set(
        brand_tweets["in_response_to_tweet_id"]
        .dropna()
        .astype(str)
    )

    customer_msgs = df[
        df["tweet_id"].astype(str).isin(reply_ids)
    ]

    matched = brand_tweets.merge(
        customer_msgs[["tweet_id", "text"]],
        left_on="in_response_to_tweet_id",
        right_on="tweet_id",
        how="inner",
        suffixes=("_brand", "_customer")
    )

    return {
        "brand": brand_name,
        "brand_replies": len(brand_tweets),
        "matched_customer_messages": len(matched),
        "coverage": (
            len(matched) / len(brand_tweets)
            if len(brand_tweets) > 0 else 0
        )
    }


brands_to_compare = [
    "AmazonHelp",
    "AppleSupport",
    "Uber_Support",
    "SpotifyCares",
    "British_Airways"
]

comparison = pd.DataFrame(
    [analyze_brand(b, df_sample) for b in brands_to_compare]
)

comparison.sort_values(
    "matched_customer_messages",
    ascending=False
)

             brand  brand_replies  matched_customer_messages  coverage
0       AmazonHelp           6924                          0       0.0
1     AppleSupport           3106                          0       0.0
2     Uber_Support           2102                          0       0.0
3     SpotifyCares           1356                          0       0.0
4  British_Airways           1156                          0       0.0

In [24]:
comparison.sort_values(
    "matched_customer_messages",
    ascending=False
)

             brand  brand_replies  matched_customer_messages  coverage
0       AmazonHelp           6924                          0       0.0
1     AppleSupport           3106                          0       0.0
2     Uber_Support           2102                          0       0.0
3     SpotifyCares           1356                          0       0.0
4  British_Airways           1156                          0       0.0

In [26]:
from pathlib import Path
import pandas as pd
import numpy as np

# Project paths
PROJECT_ROOT = Path.cwd().parent
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "twcs.csv"

print("Dataset path:")
print(DATA_PATH)

# Load only 100,000 rows for exploration
df_sample = pd.read_csv(
    DATA_PATH,
    nrows=100_000
)

print("\nDataset loaded!")
print("Shape:", df_sample.shape)

# Normalize ID columns
def normalize_id(series):
    return pd.to_numeric(
        series,
        errors="coerce"
    ).astype("Int64")


df_sample["tweet_id_num"] = normalize_id(
    df_sample["tweet_id"]
)

df_sample["response_tweet_id_num"] = normalize_id(
    df_sample["response_tweet_id"]
)

df_sample["in_response_to_tweet_id_num"] = normalize_id(
    df_sample["in_response_to_tweet_id"]
)

print("\nID normalization complete!")

Dataset path:
c:\Users\arnav\OneDrive\Desktop\hiver-ai-support-agent\data\raw\twcs.csv

Dataset loaded!
Shape: (100000, 7)

ID normalization complete!

In [27]:
from collections import Counter

company_counts = Counter()
total_rows = 0

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=200_000
):
    total_rows += len(chunk)

    company_rows = chunk[
        chunk["inbound"] == False
    ]

    company_counts.update(
        company_rows["author_id"]
        .dropna()
        .astype(str)
    )

print(f"Total rows scanned: {total_rows:,}")
print(f"Company accounts found: {len(company_counts):,}")

Total rows scanned: 2,811,774
Company accounts found: 108

In [28]:
top_brands = pd.DataFrame(
    company_counts.most_common(30),
    columns=["brand", "company_replies"]
)

top_brands

              brand  company_replies
0        AmazonHelp           169840
1      AppleSupport           106860
2      Uber_Support            56270
3      SpotifyCares            43265
4             Delta            42253
5             Tesco            38573
6       AmericanAir            36764
7       TMobileHelp            34317
8      comcastcares            33031
9   British_Airways            29361
10     SouthwestAir            28977
11     VirginTrains            27817
12     Ask_Spectrum            25860
13      XboxSupport            24557
14       sprintcare            22381
15     hulu_support            21872
16       sainsburys            19466
17          GWRHelp            19364
18   AskPlayStation            19098
19   ChipotleTweets            18749
20   VerizonSupport            17966
21          UPSHelp            17817
22       ATVIAssist            17650
23               O2            16212
24   Safaricom_Care            16077
25       idea_cares            15724
26        AskTarget            13218
27   AirAsiaSupport            12829
28        BofA_Help            12683
29          SW_Help            12231

In [29]:
BRAND = "AmazonHelp"

brand_chunks = []

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=200_000
):
    matches = chunk[
        chunk["author_id"].astype(str) == BRAND
    ]

    if not matches.empty:
        brand_chunks.append(matches)

amazon_full = pd.concat(
    brand_chunks,
    ignore_index=True
)

print("AmazonHelp tweets:", len(amazon_full))

AmazonHelp tweets: 169840

In [30]:
amazon_full[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "text",
        "response_tweet_id",
        "in_response_to_tweet_id"
    ]
].head(20)

,tweet_id,author_id,inbound,text,response_tweet_id,in_response_to_tweet_id
0,269,AmazonHelp,False,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...,"270,271",272.0
1,273,AmazonHelp,False,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...,274,271.0
2,275,AmazonHelp,False,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...,NaN,274.0
3,324,AmazonHelp,False,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...,NaN,325.0
4,615,AmazonHelp,False,@115820 I'm sorry we've let you down! Without ...,616,617.0
5,618,AmazonHelp,False,@115820 We'd like to take a further look into ...,619,616.0
6,620,AmazonHelp,False,@115822 I am unable to affect your account via...,NaN,621.0
7,622,AmazonHelp,False,"@115824 Hi, wir erhalten die Filme/Serien so v...",623,624.0
8,625,AmazonHelp,False,@115824 Wir haben zu danken. Schönen Abend noc...,NaN,623.0
9,626,AmazonHelp,False,@115826 I'm sorry for the wait. You'll receive...,627,628.0
10,629,AmazonHelp,False,@115827 Thanks for your patience. ^KM,NaN,627.0
11,631,AmazonHelp,False,@115829 I'm sorry your order arrived in this c...,NaN,632.0
12,633,AmazonHelp,False,@115831 I'm sorry for the wait. Please reach o...,NaN,634.0
13,635,AmazonHelp,False,@115832 Alexa says both styles are working for...,NaN,636.0
14,637,AmazonHelp,False,@115834 Were you able to reach us at the link ...,NaN,638.0
15,639,AmazonHelp,False,"@115834 The Echo Show is supported, please rea...",638,640.0
16,642,AmazonHelp,False,"@115834 Oh no, I'm sorry for the issues! For t...",641,643.0
17,644,AmazonHelp,False,@115835 I'm so sorry you didn't receive your p...,645,646.0
18,647,AmazonHelp,False,@115835 You can also request a call back here ...,NaN,645.0
19,648,AmazonHelp,False,@115836 Thanks for bringing this to our attent...,NaN,649.0

In [31]:
response_ids = set()

for value in amazon_full["response_tweet_id"].dropna():
    for tweet_id in str(value).split(","):
        tweet_id = tweet_id.strip()

        if tweet_id:
            response_ids.add(tweet_id)

print("Linked response tweet IDs:", len(response_ids))

Linked response tweet IDs: 100785

In [32]:
customer_chunks = []

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=200_000
):
    chunk_ids = chunk["tweet_id"].astype(str)

    matches = chunk[
        chunk_ids.isin(response_ids)
    ]

    if not matches.empty:
        customer_chunks.append(matches)

linked_tweets = pd.concat(
    customer_chunks,
    ignore_index=True
) if customer_chunks else pd.DataFrame()

print(
    "Linked tweets found:",
    len(linked_tweets)
)

Linked tweets found: 100513

In [33]:
amazon_pairs = amazon_full.merge(
    linked_tweets[
        ["tweet_id", "text", "author_id", "inbound"]
    ],
    left_on=amazon_full["response_tweet_id"]
        .astype(str)
        .str.split(",")
        .str[0],
    right_on=linked_tweets["tweet_id"].astype(str),
    how="inner",
    suffixes=("_brand", "_customer")
)

In [34]:
response_mapping = []

for _, row in amazon_full.iterrows():
    response_value = row["response_tweet_id"]

    if pd.isna(response_value):
        continue

    for response_id in str(response_value).split(","):
        response_id = response_id.strip()

        if response_id:
            response_mapping.append({
                "brand_tweet_id": str(row["tweet_id"]),
                "customer_tweet_id": response_id,
                "brand_text": row["text"]
            })

response_mapping = pd.DataFrame(response_mapping)

print(
    "Brand → linked tweet relationships:",
    len(response_mapping)
)

Brand → linked tweet relationships: 100785

In [35]:
amazon_pairs = response_mapping.merge(
    linked_tweets[
        ["tweet_id", "text", "author_id", "inbound"]
    ],
    left_on="customer_tweet_id",
    right_on=linked_tweets["tweet_id"].astype(str),
    how="inner"
)

amazon_pairs = amazon_pairs.rename(
    columns={
        "text": "customer_text"
    }
)

print("Matched AmazonHelp conversations:", len(amazon_pairs))

Matched AmazonHelp conversations: 100513

In [36]:
for _, row in amazon_pairs.head(10).iterrows():

    print("=" * 90)

    print("CUSTOMER:")
    print(row["customer_text"])

    print("\nAMAZONHELP:")
    print(row["brand_text"])

==========================================================================================
CUSTOMER:
@AmazonHelp ありがとうございます。
今、電話で主人が対応していただいてます。

AMAZONHELP:
@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET
==========================================================================================
CUSTOMER:
@AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。

AMAZONHELP:
@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET
==========================================================================================
CUSTOMER:
@AmazonHelp こちらこそありがとうございました。

AMAZONHELP:
@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET
==========================================================================================
CUSTOMER:
@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day

AMAZONHELP:
@115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN
==========================================================================================
CUSTOMER:
@AmazonHelp I frankly don't have the patience for another chat with your "customer service" people today.

AMAZONHELP:
@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG
==========================================================================================
CUSTOMER:
@AmazonHelp Okay, danke für die Info

AMAZONHELP:
@115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS
==========================================================================================
CUSTOMER:
@AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August

AMAZONHELP:
@115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ
==========================================================================================
CUSTOMER:
@AmazonHelp Hi ready for some help

AMAZONHELP:
@115834 The Echo Show is supported, please reach us for some live troubleshooting at your convenience: https://t.co/hApLpMlfHN ^DW
==========================================================================================
CUSTOMER:
@AmazonHelp Nothing there helped me with the Echo Show

AMAZONHELP:
@115834 Oh no, I'm sorry for the issues! For troubleshooting, please check out our Echo Help pages here: https://t.co/a31c4ynHES ^SG
==========================================================================================
CUSTOMER:
@AmazonHelp That page is useless - doesn’t allow me to state it hasn’t been delivered; only tells me it has! How can you sort this out?

AMAZONHELP:
@115835 I'm so sorry you didn't receive your parcel! We'd like a chance to look into this with you here: https://t.co/JzP7hlA23B ^SY

In [37]:
from collections import Counter
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "twcs.csv"

print("Dataset:", DATA_PATH)
print("Exists:", DATA_PATH.exists())

Dataset: c:\Users\arnav\OneDrive\Desktop\hiver-ai-support-agent\data\raw\twcs.csv
Exists: True

In [38]:
company_counts = Counter()
total_rows = 0

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=200_000
):
    total_rows += len(chunk)

    company_rows = chunk[chunk["inbound"] == False]

    company_counts.update(
        company_rows["author_id"].dropna().astype(str)
    )

print(f"Total rows scanned: {total_rows:,}")
print(f"Company accounts found: {len(company_counts):,}")

Total rows scanned: 2,811,774
Company accounts found: 108

In [ ]:
top_brands = pd.DataFrame(
    company_counts.most_common(30),
    columns=["brand", "company_replies"]
)

top_brands

              brand  company_replies
0        AmazonHelp           169840
1      AppleSupport           106860
2      Uber_Support            56270
3      SpotifyCares            43265
4             Delta            42253
5             Tesco            38573
6       AmericanAir            36764
7       TMobileHelp            34317
8      comcastcares            33031
9   British_Airways            29361
10     SouthwestAir            28977
11     VirginTrains            27817
12     Ask_Spectrum            25860
13      XboxSupport            24557
14       sprintcare            22381
15     hulu_support            21872
16       sainsburys            19466
17          GWRHelp            19364
18   AskPlayStation            19098
19   ChipotleTweets            18749
20   VerizonSupport            17966
21          UPSHelp            17817
22       ATVIAssist            17650
23               O2            16212
24   Safaricom_Care            16077
25       idea_cares            15724
26        AskTarget            13218
27   AirAsiaSupport            12829
28        BofA_Help            12683
29          SW_Help            12231

In [40]:
BRAND = "AmazonHelp"

brand_tweets = df_sample[
    df_sample["author_id"].astype(str) == BRAND
].copy()

print("Brand tweets:", len(brand_tweets))

Brand tweets: 6924

In [41]:
customer_tweets = df_sample[
    df_sample["inbound"] == True
].copy()

# Convert brand tweet IDs to strings
brand_ids = set(
    brand_tweets["tweet_id"].astype(str)
)

# Find customer tweets whose response_tweet_id
# points to an AmazonHelp tweet
def contains_brand_reply(value):
    if pd.isna(value):
        return False

    ids = [
        x.strip()
        for x in str(value).split(",")
    ]

    return any(x in brand_ids for x in ids)


linked_customers = customer_tweets[
    customer_tweets["response_tweet_id"]
    .apply(contains_brand_reply)
].copy()

print(
    "Customer tweets linked to AmazonHelp:",
    len(linked_customers)
)

Customer tweets linked to AmazonHelp: 6516

In [42]:
# Create one row for every Customer → AmazonHelp relationship

conversation_rows = []

for _, customer in linked_customers.iterrows():

    response_ids = [
        x.strip()
        for x in str(customer["response_tweet_id"]).split(",")
        if x.strip()
    ]

    for brand_tweet_id in response_ids:

        if brand_tweet_id in brand_ids:

            brand_row = brand_tweets[
                brand_tweets["tweet_id"].astype(str)
                == brand_tweet_id
            ]

            if not brand_row.empty:

                brand_row = brand_row.iloc[0]

                conversation_rows.append({
                    "customer_tweet_id": customer["tweet_id"],
                    "customer_text": customer["text"],
                    "brand_tweet_id": brand_row["tweet_id"],
                    "brand_text": brand_row["text"]
                })

amazon_conversations = pd.DataFrame(
    conversation_rows
)

print(
    "Customer → AmazonHelp conversations:",
    len(amazon_conversations)
)

Customer → AmazonHelp conversations: 6893

In [43]:
amazon_conversations[
    [
        "customer_text",
        "brand_text"
    ]
].head(10)

,customer_text,brand_text
0,@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...
1,@AmazonHelp こちらこそありがとうございました。,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...
2,amazonのfireTVstickが見れない😢,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...
3,amazonプライムビデオ、再生エラーが多いです,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...
4,@AmazonHelp 3 different people have given 3 di...,@115820 We'd like to take a further look into ...
5,Way to drop the ball on customer service @1158...,@115820 I'm sorry we've let you down! Without ...
6,@115823 I want my amazon payments account CLOS...,@115822 I am unable to affect your account via...
7,"@AmazonHelp Okay, danke für die Info",@115824 Wir haben zu danken. Schönen Abend noc...
8,"@115825 also, beim Addams Family-Film in Prime...","@115824 Hi, wir erhalten die Filme/Serien so v..."
9,@AmazonHelp @115826 Yeah this is crazy we’re l...,@115827 Thanks for your patience. ^KM

In [44]:
for _, row in amazon_conversations.head(5).iterrows():

    print("=" * 100)

    print("CUSTOMER:")
    print(row["customer_text"])

    print("\nAMAZONHELP:")
    print(row["brand_text"])

    print()

====================================================================================================
CUSTOMER:
@AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。

AMAZONHELP:
@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET

====================================================================================================
CUSTOMER:
@AmazonHelp こちらこそありがとうございました。

AMAZONHELP:
@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET

====================================================================================================
CUSTOMER:
amazonのfireTVstickが見れない😢

AMAZONHELP:
@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET

====================================================================================================
CUSTOMER:
amazonプライムビデオ、再生エラーが多いです

AMAZONHELP:
@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET

====================================================================================================
CUSTOMER:
@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day

AMAZONHELP:
@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG

In [45]:
# Keep only useful conversation fields
amazon_data = amazon_conversations[
    [
        "customer_tweet_id",
        "customer_text",
        "brand_tweet_id",
        "brand_text"
    ]
].copy()

# Remove missing messages
amazon_data = amazon_data.dropna(
    subset=["customer_text", "brand_text"]
)

# Convert to string
amazon_data["customer_text"] = (
    amazon_data["customer_text"]
    .astype(str)
    .str.strip()
)

amazon_data["brand_text"] = (
    amazon_data["brand_text"]
    .astype(str)
    .str.strip()
)

# Remove empty messages
amazon_data = amazon_data[
    (amazon_data["customer_text"].str.len() > 5)
]

print("Conversation pairs:", len(amazon_data))

Conversation pairs: 6893

In [46]:
amazon_data[
    ["customer_text", "brand_text"]
].head(20)

,customer_text,brand_text
0,@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...
1,@AmazonHelp こちらこそありがとうございました。,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...
2,amazonのfireTVstickが見れない😢,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...
3,amazonプライムビデオ、再生エラーが多いです,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...
4,@AmazonHelp 3 different people have given 3 di...,@115820 We'd like to take a further look into ...
5,Way to drop the ball on customer service @1158...,@115820 I'm sorry we've let you down! Without ...
6,@115823 I want my amazon payments account CLOS...,@115822 I am unable to affect your account via...
7,"@AmazonHelp Okay, danke für die Info",@115824 Wir haben zu danken. Schönen Abend noc...
8,"@115825 also, beim Addams Family-Film in Prime...","@115824 Hi, wir erhalten die Filme/Serien so v..."
9,@AmazonHelp @115826 Yeah this is crazy we’re l...,@115827 Thanks for your patience. ^KM
10,@115828 How about you guys figure out my Xbox ...,@115826 I'm sorry for the wait. You'll receive...
11,@115830 my package was ‘accidentally’ opened.....,@115829 I'm sorry your order arrived in this c...
12,@115821 @AmazonHelp why is my order at my loca...,@115831 I'm sorry for the wait. Please reach o...
13,"Thanks for the style advice, @115833 look ...I...",@115832 Alexa says both styles are working for...
14,@AmazonHelp Hi ready for some help,@115834 Were you able to reach us at the link ...
15,@AmazonHelp Is the Echo Show no longer supported?,"@115834 The Echo Show is supported, please rea..."
16,Bought an @115821 Echo Show and it won’t recog...,"@115834 Oh no, I'm sorry for the issues! For t..."
17,@AmazonHelp That page is useless - doesn’t all...,@115835 You can also request a call back here ...
18,.@AmazonHelp Item has not been delivered but t...,@115835 I'm so sorry you didn't receive your p...
19,"In response to your @115830 packing video, thi...",@115836 Thanks for bringing this to our attent...

In [47]:
generic_patterns = [
    "please help",
    "dm me",
    "sent you a dm",
    "direct message",
    "private message",
    "thank you",
    "thanks",
    "hello",
    "hi"
]

generic_mask = amazon_data["customer_text"].str.lower().apply(
    lambda text: any(pattern in text for pattern in generic_patterns)
)

print("Potentially generic messages:", generic_mask.sum())

Potentially generic messages: 2194

In [48]:
amazon_data["customer_length"] = (
    amazon_data["customer_text"]
    .str.len()
)

amazon_data["customer_length"].describe()

count    6893.000000
mean      122.249238
std        65.259938
min         7.000000
25%        72.000000
50%       119.000000
75%       152.000000
max       365.000000
Name: customer_length, dtype: float64

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words="english",
    lowercase=True,
    min_df=10,
    max_df=0.90,
    ngram_range=(1, 2),
    max_features=5000
)

X = vectorizer.fit_transform(
    amazon_data["customer_text"]
)

print("TF-IDF matrix shape:", X.shape)

TF-IDF matrix shape: (6893, 1511)

In [50]:
import numpy as np

terms = np.array(
    vectorizer.get_feature_names_out()
)

scores = np.asarray(
    X.mean(axis=0)
).ravel()

top_indices = scores.argsort()[::-1][:50]

top_terms = pd.DataFrame({
    "term": terms[top_indices],
    "tfidf_score": scores[top_indices]
})

top_terms

                term  tfidf_score
0         amazonhelp     0.090577
1              https     0.038680
2             amazon     0.027972
3             115850     0.020952
4             115821     0.020828
5              order     0.019897
6           delivery     0.018937
7              prime     0.016475
8             115830     0.013491
9                que     0.012845
10              just     0.012647
11         delivered     0.012594
12          customer     0.012237
13           service     0.012126
14              time     0.012123
15               day     0.011817
16              help     0.010996
17             today     0.010882
18              days     0.010520
19                ve     0.009924
20           package     0.009328
21             email     0.009119
22               don     0.008925
23               amp     0.008816
24            refund     0.008784
25            thanks     0.008690
26           ordered     0.008656
27                la     0.008548
28               got     0.008431
29           product     0.008145
30           account     0.007734
31          received     0.007231
32              need     0.007149
33                en     0.007142
34              says     0.007008
35               did     0.006876
36              want     0.006841
37               yes     0.006803
38             issue     0.006633
39                el     0.006442
40              item     0.006427
41  customer service     0.006312
42              like     0.006294
43              guys     0.006240
44            return     0.006233
45             thank     0.006164
46          shipping     0.006016
47              know     0.005997
48  amazonhelp https     0.005938
49             going     0.005928

In [51]:
from sklearn.cluster import KMeans

n_clusters = 12

kmeans = KMeans(
    n_clusters=n_clusters,
    random_state=42,
    n_init=10
)

amazon_data["cluster"] = kmeans.fit_predict(X)

print("Clusters created:", n_clusters)

Clusters created: 12

In [52]:
order_centroids = kmeans.cluster_centers_.argsort()[:, ::-1]

for cluster_id in range(n_clusters):

    top_words = terms[
        order_centroids[cluster_id, :10]
    ]

    print(
        f"\nCluster {cluster_id}:"
    )
    print(", ".join(top_words))

Cluster 0:
115821, delivery, day, 115830, prime, https, shipping, package, days, ordered

Cluster 1:
amazonhelp, 115851, worth, 115830, 115830 amazonhelp, yo, 00, ça, 115825, 115821 prime

Cluster 2:
ich, nicht, die, 116316, und, das, ist, es, der, für

Cluster 3:
https, amazonhelp https, amazonhelp, amazon, 119625, check, 115830, 120533, 115821, 11

Cluster 4:
delivered, amazonhelp, delivery, package, today, delivered today, order, says, item, day

Cluster 5:
que, el, en, la, lo, 116875, mi, por, se, 116928

Cluster 6:
amazonhelp, https, just, ve, yes, help, thanks, email, time, amazonhelp yes

Cluster 7:
amazon, amazonhelp, amazonhelp amazon, amazon prime, prime, https, india, amazon logistics, logistics, 115821

Cluster 8:
115850, https, amazon, amazonhelp 115850, 115850 amazonhelp, 115851, amazonhelp, product, refund, 115821

Cluster 9:
order, amazonhelp, amazonhelp order, 115850, delivery, amazon, https, placed, 115850 order, cancelled

Cluster 10:
le, je, est, pas, et, 120533, ai, pour, vous, la

Cluster 11:
customer, customer service, service, customer care, care, amazonhelp, support, amazon, 115850, amazonhelp customer

In [53]:
for cluster_id in range(n_clusters):

    print("\n" + "=" * 100)
    print(f"CLUSTER {cluster_id}")

    examples = amazon_data[
        amazon_data["cluster"] == cluster_id
    ]["customer_text"].head(5)

    for example in examples:
        print("-", example)

====================================================================================================
CLUSTER 0
- @115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away
- @115830 my package was ‘accidentally’ opened.. 4 items missing worth £97.
You need better delivery drivers!! https://t.co/f6SaVBSMqM
- Bought an @115821 Echo Show and it won’t recognize a single @AmazonHelp account in our household. WTF, guys?
- In response to your @115830 packing video, this packaging was for a 2ft washing line pole @115837 https://t.co/X21SQHgC0K
- @115821, it’d be nice if the book I waited 4 months for wasn’t damaged inside of an undented box. #twinpeaks #twin… https://t.co/Lac4K7iQzJ https://t.co/JroqJKrH9Q

====================================================================================================
CLUSTER 1
- @AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。
- @AmazonHelp こちらこそありがとうございました。
- @AmazonHelp I have. No luck.
- @AmazonHelp ご丁寧にありがとうございます！トライしてみて改善されなければCSへご連絡します。返信いただけると思っていなかったので本当に嬉しいです！
- @AmazonHelp All of them

====================================================================================================
CLUSTER 2
- @AmazonHelp Okay, danke für die Info
- @115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?
- @AmazonHelp Kann ich dann wenigstens mein Amazon-Konto aufladen um zu bezahlen. Ich habe keine Kreditkarte und möchte auch keine
- @AmazonHelp Warum ist es mir (und scheinbar auch ein paar anderen) nicht möglich per Bankeinzug zu bezahlen?
- @AmazonHelp Danke für die schnelle Antwort... ja, ich werde mal nachfragen, was da schiefgelaufen sein soll. Ihnen auch einen schönen Abend noch.

====================================================================================================
CLUSTER 3
- @115841 @115821 Feliz #Halloween2017 https://t.co/edHbRDnM8x
- @117093 #HappyHalloween2017 from your biggest fan. Thank you for creating #efficient and #healthy households nationwide! https://t.co/06sKXnGayh
- ねぇこういうのマジで頭悪いと思うんだよね。じゃあ具体的にどんなサイトにいつどの端末から登録したのか訊けば答えられるんかね。そのサイトのアクセスログに俺のIPアドレスは載ってるんかね。そもそもAmazonは「有料動画サイト」とかやってねぇよバカか。 https://t.co/kz68UogX2A
- Please explain this @AmazonHelp https://t.co/VJ4d1ii4PH
- Amazonから明日配達予定だったHDDが届いたんだけど、箱の中のクッション意味あるの？
何の役にもたってないんだけど。
品物が衝撃に弱い精密機器ってわかって梱包してんの？
配達の軽トラの荷台で何時間も衝撃にさらされたHDDですか。 https://t.co/DcqV2uV0we

====================================================================================================
CLUSTER 4
- @AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day
- @115821 @AmazonHelp why is my order at my local courier for the last 6 days and still hasn’t been delivered to me?? Over 1 week late 😡
- @AmazonHelp That page is useless - doesn’t allow me to state it hasn’t been delivered; only tells me it has! How can you sort this out?
- .@AmazonHelp Item has not been delivered but tracking says it was handed to me over an hour ago... 2nd time this has happened. Sort it out https://t.co/42W82GcARk
- @AmazonHelp Hi, I ordered an item on 18 Oct which said it would be delivered by 20 Oct and I still haven't received it. Can you help? Thanks

====================================================================================================
CLUSTER 5
- @AmazonHelp na ultima atualização da entrega do meu pedido, consta que não foi possível localizar o meu endereço, poderia ajudar?
- @AmazonHelp Solo dice “en reparto” pero no tiene un número de contacto con el repartidor que es de Amazon Services 😩
- @116875 ¿como puedo trackear si esta próximo a ser entregado un paquete que tiene fecha de hoy? Gracias
- Jamas volvere a comprar en @116875 :'v
- Que hueva tendré que veré vaselina por Amazon prime video. Obvio me pasan una lana por promocionar prime video @116928

====================================================================================================
CLUSTER 6
- amazonのfireTVstickが見れない😢
- amazonプライムビデオ、再生エラーが多いです
- @AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August
- Thanks for the style advice, @115833 look ...I think? #Halloween2017 #flamingo https://t.co/XvI54La043
- @AmazonHelp Hi ready for some help

====================================================================================================
CLUSTER 7
- @115823 I want my amazon payments account CLOSED.  dm me please.
- @AmazonHelp since when you stop giving 20% off videogame pre-orders (amazon prime members) im confused? why?
- Just pulled another #Amazon delivery out of the bushes since the #amzl people can’t walk the extra 2 ft to my door. So tired of this.
- @115821 being charged for amazon prime &amp; when I go to cancel it, it’s saying I’m not a member😠😠😠
- I ordered some parts of my costume late, but my amazon has a map of the driver and they're like, 6 houses away.

====================================================================================================
CLUSTER 8
- @115850 @115821 @AmazonHelp @115851 Order# 3632693-6196346. You couldn't deliver EVEN AFTER A MONTH. You should be ashamed of yourself.
- @115850 @115850 is one of the best app in the world
- @115850 का एकाउंट परमानेंटली डिलीट कैसे करते है?
- @115850 I have stopped ordering from your site, Amazon courier guys are very rude. I have given similar complaints to u no of tyms.
- @115850 I have stopped ordering from your site, Amazon courier guys are very rude. I have given similar complaints to u no of tyms.

====================================================================================================
CLUSTER 9
- @AmazonHelp Already started the return. UPS gets it from my doorstep tomorrow. Order 111-5014070-4118645
- @115845 They sent the feckin' order to Germany! Some dozy driver is looking for an address in the wrong country! I'm so done with Amazon!
- @AmazonHelp but I can’t find the options to cancel or re-order?
- @115821 my order hasn’t arrived (it was due 14th October). Can you help?
- @AmazonHelp if I add another adult to my Amazon household (with their own account) can they see my wishlists/photos/order history?

====================================================================================================
CLUSTER 10
- @120533 @120534 J'ai demandé le remboursement @120533
Coucou @120535 plus la peine de vous pointer (si un jour vous pensiez vraiment livrer)
- @AmazonHelp oui c'est dommage j'en avais absolument besoin aujourdhui, Chronopost ou UPS l'aurait laissé chez le voisin ou dans un commerce de proximité
- Bonjour @120533 ! C’est fâcheux de prendre La Poste pour les livraisons expresses la veille des jours fériés... https://t.co/aULnltgh5W
- @AmazonHelp Le SAV m'a dit hier qu'ils allaient accélérer l'expédition, mais c'est toujours pas expédié... c'est vraiment n'importe quoi Amazon
- @AmazonHelp J'ai voulu annuler ma commande, mais Amazon dit que c'est soit disant trop tard... Vraiment barbant chez Amazon ! Que des problèmes!

====================================================================================================
CLUSTER 11
- Way to drop the ball on customer service @115821 so pissed right now!
- @AmazonHelp Thats the thing I told customer service. I created a new email address for the Prime trial and forgot it. What can I do so I'm not charged?
- @AmazonHelp I called customer service and was told my membership wouldn't be renewed. I was just charged today. How do I get a refund? https://t.co/SeoQUsA0VA
- @116090 Saying I preordered to early, terrible customer service. Won’t renew prime if this isn’t fixed.
- @AmazonHelp i mailed amazonuk so many time. but i havent got any progress.customer care just saying thats in the billing section.no i havent got refund

In [54]:
INTENTS = {
    "refund_status": "Customer asking about a pending or missing refund.",
    "delivery_issue": "Customer reporting a delayed, missing, or late delivery.",
    "payment_issue": "Customer reporting a charge, payment, or billing problem.",
    "account_issue": "Customer having trouble accessing or managing their account.",
    # ...
}

In [55]:
for cluster_id in range(n_clusters):
    ...

In [56]:
# Show actual examples from every discovered cluster

for cluster_id in sorted(amazon_data["cluster"].unique()):

    print("\n" + "=" * 100)
    print(f"CLUSTER {cluster_id}")

    examples = amazon_data[
        amazon_data["cluster"] == cluster_id
    ]["customer_text"].head(8)

    for i, example in enumerate(examples, 1):
        print(f"{i}. {example}")

====================================================================================================
CLUSTER 0
1. @115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away
2. @115830 my package was ‘accidentally’ opened.. 4 items missing worth £97.
You need better delivery drivers!! https://t.co/f6SaVBSMqM
3. Bought an @115821 Echo Show and it won’t recognize a single @AmazonHelp account in our household. WTF, guys?
4. In response to your @115830 packing video, this packaging was for a 2ft washing line pole @115837 https://t.co/X21SQHgC0K
5. @115821, it’d be nice if the book I waited 4 months for wasn’t damaged inside of an undented box. #twinpeaks #twin… https://t.co/Lac4K7iQzJ https://t.co/JroqJKrH9Q
6. @AmazonHelp delivery I paid for today,didn’t arrive.why not?i paid enough for it.where is it??I’m unhappy.refund the delivery charge
7. Anna Inspired in idea lab at school to be @115821 package being shipped to Narnia! "Amazon can go anywhere" according to Anna. https://t.co/TyvKhuu7su
8. @115847 @115821 Yeah idk the shipping company and it says “mike Ziemer” signed for it in the mail room at our building lol

====================================================================================================
CLUSTER 1
1. @AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。
2. @AmazonHelp こちらこそありがとうございました。
3. @AmazonHelp I have. No luck.
4. @AmazonHelp ご丁寧にありがとうございます！トライしてみて改善されなければCSへご連絡します。返信いただけると思っていなかったので本当に嬉しいです！
5. @AmazonHelp All of them
6. @AmazonHelp アカウント凍結して不正アクセスを調べてもらうことになりました。
ありがとうございました。
7. @AmazonHelp 親切にどうもありがとうございます(;_;)(;_;)
8. @AmazonHelp 今までコンビニで支払いが出きるという支払い方法でAmazonさんにお世話になっていたんですけど、選択画面にその支払い方法が表示されなくて、色々いじってみたんですけどどうにも……！

====================================================================================================
CLUSTER 2
1. @AmazonHelp Okay, danke für die Info
2. @115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?
3. @AmazonHelp Kann ich dann wenigstens mein Amazon-Konto aufladen um zu bezahlen. Ich habe keine Kreditkarte und möchte auch keine
4. @AmazonHelp Warum ist es mir (und scheinbar auch ein paar anderen) nicht möglich per Bankeinzug zu bezahlen?
5. @AmazonHelp Danke für die schnelle Antwort... ja, ich werde mal nachfragen, was da schiefgelaufen sein soll. Ihnen auch einen schönen Abend noch.
6. Ach schau an. Meine Bestellung war unzustellbar... @AmazonHelp, was ist da denn passiert? Bekomme ich mein Geld nun wieder?
7. @AmazonHelp Schnippig ist sie auch noch? Wird ja immer interessanter 😅
8. .@116316 ist mal wieder on fire. https://t.co/lUURAjsRKQ

====================================================================================================
CLUSTER 3
1. @115841 @115821 Feliz #Halloween2017 https://t.co/edHbRDnM8x
2. @117093 #HappyHalloween2017 from your biggest fan. Thank you for creating #efficient and #healthy households nationwide! https://t.co/06sKXnGayh
3. ねぇこういうのマジで頭悪いと思うんだよね。じゃあ具体的にどんなサイトにいつどの端末から登録したのか訊けば答えられるんかね。そのサイトのアクセスログに俺のIPアドレスは載ってるんかね。そもそもAmazonは「有料動画サイト」とかやってねぇよバカか。 https://t.co/kz68UogX2A
4. Please explain this @AmazonHelp https://t.co/VJ4d1ii4PH
5. Amazonから明日配達予定だったHDDが届いたんだけど、箱の中のクッション意味あるの？
何の役にもたってないんだけど。
品物が衝撃に弱い精密機器ってわかって梱包してんの？
配達の軽トラの荷台で何時間も衝撃にさらされたHDDですか。 https://t.co/DcqV2uV0we
6. Amazon梱包雑になったぞおおおおおお！？！？ https://t.co/flImzUdwwk
7. そういえば、電熱ヒーターもどきをAmazonで買ってたな。寒くなったし試すか。(´ω｀)

あったー😹えっ、…入らない😿

いや、でもヒーター部分は使えるかも❕❗❕

…縫い糸がケーブル貫通しとるやないかーい😂

まあ、400円だから…またなんか探そっと😸

皆さんも防寒対策お気をつけください🙋 https://t.co/b7tvSIEeGm
8. そういえば、電熱ヒーターもどきをAmazonで買ってたな。寒くなったし試すか。(´ω｀)

あったー😹えっ、…入らない😿

いや、でもヒーター部分は使えるかも❕❗❕

…縫い糸がケーブル貫通しとるやないかーい😂

まあ、400円だから…またなんか探そっと😸

皆さんも防寒対策お気をつけください🙋 https://t.co/b7tvSIEeGm

====================================================================================================
CLUSTER 4
1. @AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day
2. @115821 @AmazonHelp why is my order at my local courier for the last 6 days and still hasn’t been delivered to me?? Over 1 week late 😡
3. @AmazonHelp That page is useless - doesn’t allow me to state it hasn’t been delivered; only tells me it has! How can you sort this out?
4. .@AmazonHelp Item has not been delivered but tracking says it was handed to me over an hour ago... 2nd time this has happened. Sort it out https://t.co/42W82GcARk
5. @AmazonHelp Hi, I ordered an item on 18 Oct which said it would be delivered by 20 Oct and I still haven't received it. Can you help? Thanks
6. Got 2 packages delivered today from @115821 via their AMZL service. One package gets dumped at Leasing Office, which is not the address on package &amp; 1 package gets delivered to address on package, which is my apartment. 2 drivers, different results. I was home all day.
7. @AmazonHelp AMZL US Tracking ID TBA566517950000 it says delivered to mail room, I checked the mail and the front offce, the driver listed 1 package, in that one package was my XLR cables...I'm missing the controller.
8. @115821 the more I order from you guys, the more I'm going to stop being a customer....YOUR DRIVERS ARE USELESS. Once again they marked a package delivered when it clearly wasn't. I received one of two packages, yet they were both marked delivered. 3 times in 1 month! https://t.co/9UYVHPVWtE

====================================================================================================
CLUSTER 5
1. @AmazonHelp na ultima atualização da entrega do meu pedido, consta que não foi possível localizar o meu endereço, poderia ajudar?
2. @AmazonHelp Solo dice “en reparto” pero no tiene un número de contacto con el repartidor que es de Amazon Services 😩
3. @116875 ¿como puedo trackear si esta próximo a ser entregado un paquete que tiene fecha de hoy? Gracias
4. Jamas volvere a comprar en @116875 :'v
5. Que hueva tendré que veré vaselina por Amazon prime video. Obvio me pasan una lana por promocionar prime video @116928
6. @AmazonHelp Pago para tener el Prime con vosotros para que me tarden en llegar 10 dias? Reembolsadme la compra y lo compro en cualquier otro sitio
7. @AmazonHelp Hecho el procedimiento, lo que me interesa y exijo es que sea devuelto mi dinero puesto que jamás he adquirido algún articulo por este medio
8. @116875 Exijo mi reembolso inmediato ya que yo en ningún momento solicité dicha membresía "prime", hubo algún error.
Solución inmediata

====================================================================================================
CLUSTER 6
1. amazonのfireTVstickが見れない😢
2. amazonプライムビデオ、再生エラーが多いです
3. @AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August
4. Thanks for the style advice, @115833 look ...I think? #Halloween2017 #flamingo https://t.co/XvI54La043
5. @AmazonHelp Hi ready for some help
6. @AmazonHelp Is the Echo Show no longer supported?
7. @AmazonHelp I don't want a form to fill out that logs a response no one reads. I want to prevent AMZL from touching my stuff. Possible, or no?
8. @AmazonHelp Is it possible to prevent AMZL from delivering my packages moving forward? Stuff is either lost/stolen/broken EVERY time.

====================================================================================================
CLUSTER 7
1. @115823 I want my amazon payments account CLOSED.  dm me please.
2. @AmazonHelp since when you stop giving 20% off videogame pre-orders (amazon prime members) im confused? why?
3. Just pulled another #Amazon delivery out of the bushes since the #amzl people can’t walk the extra 2 ft to my door. So tired of this.
4. @115821 being charged for amazon prime &amp; when I go to cancel it, it’s saying I’m not a member😠😠😠
5. I ordered some parts of my costume late, but my amazon has a map of the driver and they're like, 6 houses away.
6. @AmazonHelp Fulfilled by Amazon. It’s quite disturbing you’re selling counterfeit items, and can’t be trusted.
7. Two fake items in one day. Time to cancel my Amazon Prime membership. @AmazonHelp
8. @AmazonHelp It’s not allowing me to update it to register my new amazon account. I read I’d have to do so manually. Thx 4 response.

====================================================================================================
CLUSTER 8
1. @115850 @115821 @AmazonHelp @115851 Order# 3632693-6196346. You couldn't deliver EVEN AFTER A MONTH. You should be ashamed of yourself.
2. @115850 @115850 is one of the best app in the world
3. @115850 का एकाउंट परमानेंटली डिलीट कैसे करते है?
4. @115850 I have stopped ordering from your site, Amazon courier guys are very rude. I have given similar complaints to u no of tyms.
5. @115850 I have stopped ordering from your site, Amazon courier guys are very rude. I have given similar complaints to u no of tyms.
6. @115850 pls investigate ur satara (Maharashtra) amzn staff or ur reputation is doomed in the region in long term.
7. @115850 I mean I don't have problem with most of the orders but the black dot moving with the green bar is quite irritating
8. @115850 why to you promise false discounts with wrong mrp ...the device I bought showed a mrp of 7999 when its actual mrp is 7499 https://t.co/1kqHQVHBcl

====================================================================================================
CLUSTER 9
1. @AmazonHelp Already started the return. UPS gets it from my doorstep tomorrow. Order 111-5014070-4118645
2. @115845 They sent the feckin' order to Germany! Some dozy driver is looking for an address in the wrong country! I'm so done with Amazon!
3. @AmazonHelp but I can’t find the options to cancel or re-order?
4. @115821 my order hasn’t arrived (it was due 14th October). Can you help?
5. @AmazonHelp if I add another adult to my Amazon household (with their own account) can they see my wishlists/photos/order history?
6. Seriously @115821? I order 6 identical washing up bowls and they are all being dispatched as separate orders? My phone is buzzing non-stop!
7. @AmazonHelp hello, I’m having an issue with a same day ship order.  Can you help me?
8. @AmazonHelp Where is my order? https://t.co/pXnKSCo2ex

====================================================================================================
CLUSTER 10
1. @120533 @120534 J'ai demandé le remboursement @120533
Coucou @120535 plus la peine de vous pointer (si un jour vous pensiez vraiment livrer)
2. @AmazonHelp oui c'est dommage j'en avais absolument besoin aujourdhui, Chronopost ou UPS l'aurait laissé chez le voisin ou dans un commerce de proximité
3. Bonjour @120533 ! C’est fâcheux de prendre La Poste pour les livraisons expresses la veille des jours fériés... https://t.co/aULnltgh5W
4. @AmazonHelp Le SAV m'a dit hier qu'ils allaient accélérer l'expédition, mais c'est toujours pas expédié... c'est vraiment n'importe quoi Amazon
5. @AmazonHelp J'ai voulu annuler ma commande, mais Amazon dit que c'est soit disant trop tard... Vraiment barbant chez Amazon ! Que des problèmes!
6. @AmazonHelp Où dois puis-je trouver votre SAV? c'est introuvable sur votre site...
7. @AmazonHelp Hier c'était écrit "envoi aujourd'hui" dans le suivi, et ça n'a pas été expédié hier... #troll
8. Je ne vois vraiment pas l'intérêt d'avoir prime... (article en stock et expédié par Amazon) @AmazonHelp https://t.co/4pnOr895TR

====================================================================================================
CLUSTER 11
1. Way to drop the ball on customer service @115821 so pissed right now!
2. @AmazonHelp Thats the thing I told customer service. I created a new email address for the Prime trial and forgot it. What can I do so I'm not charged?
3. @AmazonHelp I called customer service and was told my membership wouldn't be renewed. I was just charged today. How do I get a refund? https://t.co/SeoQUsA0VA
4. @116090 Saying I preordered to early, terrible customer service. Won’t renew prime if this isn’t fixed.
5. @AmazonHelp i mailed amazonuk so many time. but i havent got any progress.customer care just saying thats in the billing section.no i havent got refund
6. @AmazonHelp how is Amazon going to solve this? By mail, text, call, customer phone service, no one is able to help me https://t.co/jhzCjY2bOw
7. @AmazonHelp I have no option but to see if my delivery arrives on the scheduled date. But I will contact customer services if it doesn't arrive on time.
8. @AmazonHelp No, I can't check. It shows nothing. And customer service rep was NO help.

In [57]:
for cluster_id in sorted(amazon_data["cluster"].unique()):

    print("\n" + "=" * 100)
    print(f"CLUSTER {cluster_id}")

    examples = amazon_data[
        amazon_data["cluster"] == cluster_id
    ]["customer_text"].head(8)

    for i, example in enumerate(examples, 1):
        print(f"{i}. {example}")

====================================================================================================
CLUSTER 0
1. @115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away
2. @115830 my package was ‘accidentally’ opened.. 4 items missing worth £97.
You need better delivery drivers!! https://t.co/f6SaVBSMqM
3. Bought an @115821 Echo Show and it won’t recognize a single @AmazonHelp account in our household. WTF, guys?
4. In response to your @115830 packing video, this packaging was for a 2ft washing line pole @115837 https://t.co/X21SQHgC0K
5. @115821, it’d be nice if the book I waited 4 months for wasn’t damaged inside of an undented box. #twinpeaks #twin… https://t.co/Lac4K7iQzJ https://t.co/JroqJKrH9Q
6. @AmazonHelp delivery I paid for today,didn’t arrive.why not?i paid enough for it.where is it??I’m unhappy.refund the delivery charge
7. Anna Inspired in idea lab at school to be @115821 package being shipped to Narnia! "Amazon can go anywhere" according to Anna. https://t.co/TyvKhuu7su
8. @115847 @115821 Yeah idk the shipping company and it says “mike Ziemer” signed for it in the mail room at our building lol

====================================================================================================
CLUSTER 1
1. @AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。
2. @AmazonHelp こちらこそありがとうございました。
3. @AmazonHelp I have. No luck.
4. @AmazonHelp ご丁寧にありがとうございます！トライしてみて改善されなければCSへご連絡します。返信いただけると思っていなかったので本当に嬉しいです！
5. @AmazonHelp All of them
6. @AmazonHelp アカウント凍結して不正アクセスを調べてもらうことになりました。
ありがとうございました。
7. @AmazonHelp 親切にどうもありがとうございます(;_;)(;_;)
8. @AmazonHelp 今までコンビニで支払いが出きるという支払い方法でAmazonさんにお世話になっていたんですけど、選択画面にその支払い方法が表示されなくて、色々いじってみたんですけどどうにも……！

====================================================================================================
CLUSTER 2
1. @AmazonHelp Okay, danke für die Info
2. @115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?
3. @AmazonHelp Kann ich dann wenigstens mein Amazon-Konto aufladen um zu bezahlen. Ich habe keine Kreditkarte und möchte auch keine
4. @AmazonHelp Warum ist es mir (und scheinbar auch ein paar anderen) nicht möglich per Bankeinzug zu bezahlen?
5. @AmazonHelp Danke für die schnelle Antwort... ja, ich werde mal nachfragen, was da schiefgelaufen sein soll. Ihnen auch einen schönen Abend noch.
6. Ach schau an. Meine Bestellung war unzustellbar... @AmazonHelp, was ist da denn passiert? Bekomme ich mein Geld nun wieder?
7. @AmazonHelp Schnippig ist sie auch noch? Wird ja immer interessanter 😅
8. .@116316 ist mal wieder on fire. https://t.co/lUURAjsRKQ

====================================================================================================
CLUSTER 3
1. @115841 @115821 Feliz #Halloween2017 https://t.co/edHbRDnM8x
2. @117093 #HappyHalloween2017 from your biggest fan. Thank you for creating #efficient and #healthy households nationwide! https://t.co/06sKXnGayh
3. ねぇこういうのマジで頭悪いと思うんだよね。じゃあ具体的にどんなサイトにいつどの端末から登録したのか訊けば答えられるんかね。そのサイトのアクセスログに俺のIPアドレスは載ってるんかね。そもそもAmazonは「有料動画サイト」とかやってねぇよバカか。 https://t.co/kz68UogX2A
4. Please explain this @AmazonHelp https://t.co/VJ4d1ii4PH
5. Amazonから明日配達予定だったHDDが届いたんだけど、箱の中のクッション意味あるの？
何の役にもたってないんだけど。
品物が衝撃に弱い精密機器ってわかって梱包してんの？
配達の軽トラの荷台で何時間も衝撃にさらされたHDDですか。 https://t.co/DcqV2uV0we
6. Amazon梱包雑になったぞおおおおおお！？！？ https://t.co/flImzUdwwk
7. そういえば、電熱ヒーターもどきをAmazonで買ってたな。寒くなったし試すか。(´ω｀)

あったー😹えっ、…入らない😿

いや、でもヒーター部分は使えるかも❕❗❕

…縫い糸がケーブル貫通しとるやないかーい😂

まあ、400円だから…またなんか探そっと😸

皆さんも防寒対策お気をつけください🙋 https://t.co/b7tvSIEeGm
8. そういえば、電熱ヒーターもどきをAmazonで買ってたな。寒くなったし試すか。(´ω｀)

あったー😹えっ、…入らない😿

いや、でもヒーター部分は使えるかも❕❗❕

…縫い糸がケーブル貫通しとるやないかーい😂

まあ、400円だから…またなんか探そっと😸

皆さんも防寒対策お気をつけください🙋 https://t.co/b7tvSIEeGm

====================================================================================================
CLUSTER 4
1. @AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day
2. @115821 @AmazonHelp why is my order at my local courier for the last 6 days and still hasn’t been delivered to me?? Over 1 week late 😡
3. @AmazonHelp That page is useless - doesn’t allow me to state it hasn’t been delivered; only tells me it has! How can you sort this out?
4. .@AmazonHelp Item has not been delivered but tracking says it was handed to me over an hour ago... 2nd time this has happened. Sort it out https://t.co/42W82GcARk
5. @AmazonHelp Hi, I ordered an item on 18 Oct which said it would be delivered by 20 Oct and I still haven't received it. Can you help? Thanks
6. Got 2 packages delivered today from @115821 via their AMZL service. One package gets dumped at Leasing Office, which is not the address on package &amp; 1 package gets delivered to address on package, which is my apartment. 2 drivers, different results. I was home all day.
7. @AmazonHelp AMZL US Tracking ID TBA566517950000 it says delivered to mail room, I checked the mail and the front offce, the driver listed 1 package, in that one package was my XLR cables...I'm missing the controller.
8. @115821 the more I order from you guys, the more I'm going to stop being a customer....YOUR DRIVERS ARE USELESS. Once again they marked a package delivered when it clearly wasn't. I received one of two packages, yet they were both marked delivered. 3 times in 1 month! https://t.co/9UYVHPVWtE

====================================================================================================
CLUSTER 5
1. @AmazonHelp na ultima atualização da entrega do meu pedido, consta que não foi possível localizar o meu endereço, poderia ajudar?
2. @AmazonHelp Solo dice “en reparto” pero no tiene un número de contacto con el repartidor que es de Amazon Services 😩
3. @116875 ¿como puedo trackear si esta próximo a ser entregado un paquete que tiene fecha de hoy? Gracias
4. Jamas volvere a comprar en @116875 :'v
5. Que hueva tendré que veré vaselina por Amazon prime video. Obvio me pasan una lana por promocionar prime video @116928
6. @AmazonHelp Pago para tener el Prime con vosotros para que me tarden en llegar 10 dias? Reembolsadme la compra y lo compro en cualquier otro sitio
7. @AmazonHelp Hecho el procedimiento, lo que me interesa y exijo es que sea devuelto mi dinero puesto que jamás he adquirido algún articulo por este medio
8. @116875 Exijo mi reembolso inmediato ya que yo en ningún momento solicité dicha membresía "prime", hubo algún error.
Solución inmediata

====================================================================================================
CLUSTER 6
1. amazonのfireTVstickが見れない😢
2. amazonプライムビデオ、再生エラーが多いです
3. @AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August
4. Thanks for the style advice, @115833 look ...I think? #Halloween2017 #flamingo https://t.co/XvI54La043
5. @AmazonHelp Hi ready for some help
6. @AmazonHelp Is the Echo Show no longer supported?
7. @AmazonHelp I don't want a form to fill out that logs a response no one reads. I want to prevent AMZL from touching my stuff. Possible, or no?
8. @AmazonHelp Is it possible to prevent AMZL from delivering my packages moving forward? Stuff is either lost/stolen/broken EVERY time.

====================================================================================================
CLUSTER 7
1. @115823 I want my amazon payments account CLOSED.  dm me please.
2. @AmazonHelp since when you stop giving 20% off videogame pre-orders (amazon prime members) im confused? why?
3. Just pulled another #Amazon delivery out of the bushes since the #amzl people can’t walk the extra 2 ft to my door. So tired of this.
4. @115821 being charged for amazon prime &amp; when I go to cancel it, it’s saying I’m not a member😠😠😠
5. I ordered some parts of my costume late, but my amazon has a map of the driver and they're like, 6 houses away.
6. @AmazonHelp Fulfilled by Amazon. It’s quite disturbing you’re selling counterfeit items, and can’t be trusted.
7. Two fake items in one day. Time to cancel my Amazon Prime membership. @AmazonHelp
8. @AmazonHelp It’s not allowing me to update it to register my new amazon account. I read I’d have to do so manually. Thx 4 response.

====================================================================================================
CLUSTER 8
1. @115850 @115821 @AmazonHelp @115851 Order# 3632693-6196346. You couldn't deliver EVEN AFTER A MONTH. You should be ashamed of yourself.
2. @115850 @115850 is one of the best app in the world
3. @115850 का एकाउंट परमानेंटली डिलीट कैसे करते है?
4. @115850 I have stopped ordering from your site, Amazon courier guys are very rude. I have given similar complaints to u no of tyms.
5. @115850 I have stopped ordering from your site, Amazon courier guys are very rude. I have given similar complaints to u no of tyms.
6. @115850 pls investigate ur satara (Maharashtra) amzn staff or ur reputation is doomed in the region in long term.
7. @115850 I mean I don't have problem with most of the orders but the black dot moving with the green bar is quite irritating
8. @115850 why to you promise false discounts with wrong mrp ...the device I bought showed a mrp of 7999 when its actual mrp is 7499 https://t.co/1kqHQVHBcl

====================================================================================================
CLUSTER 9
1. @AmazonHelp Already started the return. UPS gets it from my doorstep tomorrow. Order 111-5014070-4118645
2. @115845 They sent the feckin' order to Germany! Some dozy driver is looking for an address in the wrong country! I'm so done with Amazon!
3. @AmazonHelp but I can’t find the options to cancel or re-order?
4. @115821 my order hasn’t arrived (it was due 14th October). Can you help?
5. @AmazonHelp if I add another adult to my Amazon household (with their own account) can they see my wishlists/photos/order history?
6. Seriously @115821? I order 6 identical washing up bowls and they are all being dispatched as separate orders? My phone is buzzing non-stop!
7. @AmazonHelp hello, I’m having an issue with a same day ship order.  Can you help me?
8. @AmazonHelp Where is my order? https://t.co/pXnKSCo2ex

====================================================================================================
CLUSTER 10
1. @120533 @120534 J'ai demandé le remboursement @120533
Coucou @120535 plus la peine de vous pointer (si un jour vous pensiez vraiment livrer)
2. @AmazonHelp oui c'est dommage j'en avais absolument besoin aujourdhui, Chronopost ou UPS l'aurait laissé chez le voisin ou dans un commerce de proximité
3. Bonjour @120533 ! C’est fâcheux de prendre La Poste pour les livraisons expresses la veille des jours fériés... https://t.co/aULnltgh5W
4. @AmazonHelp Le SAV m'a dit hier qu'ils allaient accélérer l'expédition, mais c'est toujours pas expédié... c'est vraiment n'importe quoi Amazon
5. @AmazonHelp J'ai voulu annuler ma commande, mais Amazon dit que c'est soit disant trop tard... Vraiment barbant chez Amazon ! Que des problèmes!
6. @AmazonHelp Où dois puis-je trouver votre SAV? c'est introuvable sur votre site...
7. @AmazonHelp Hier c'était écrit "envoi aujourd'hui" dans le suivi, et ça n'a pas été expédié hier... #troll
8. Je ne vois vraiment pas l'intérêt d'avoir prime... (article en stock et expédié par Amazon) @AmazonHelp https://t.co/4pnOr895TR

====================================================================================================
CLUSTER 11
1. Way to drop the ball on customer service @115821 so pissed right now!
2. @AmazonHelp Thats the thing I told customer service. I created a new email address for the Prime trial and forgot it. What can I do so I'm not charged?
3. @AmazonHelp I called customer service and was told my membership wouldn't be renewed. I was just charged today. How do I get a refund? https://t.co/SeoQUsA0VA
4. @116090 Saying I preordered to early, terrible customer service. Won’t renew prime if this isn’t fixed.
5. @AmazonHelp i mailed amazonuk so many time. but i havent got any progress.customer care just saying thats in the billing section.no i havent got refund
6. @AmazonHelp how is Amazon going to solve this? By mail, text, call, customer phone service, no one is able to help me https://t.co/jhzCjY2bOw
7. @AmazonHelp I have no option but to see if my delivery arrives on the scheduled date. But I will contact customer services if it doesn't arrive on time.
8. @AmazonHelp No, I can't check. It shows nothing. And customer service rep was NO help.