In [3]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "amazonhelp_conversations.csv"
)

amazon_data = pd.read_csv(DATA_PATH)

print(amazon_data.shape)

amazon_data.head()

(168814, 5)

,customer_tweet_id,customer_text,brand_tweet_id,brand_text,brand_name
0,271,@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...,273,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...,AmazonHelp
1,274,@AmazonHelp こちらこそありがとうございました。,275,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...,AmazonHelp
2,272,amazonのfireTVstickが見れない😢,269,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...,AmazonHelp
3,325,amazonプライムビデオ、再生エラーが多いです,324,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...,AmazonHelp
4,616,@AmazonHelp 3 different people have given 3 di...,618,@115820 We'd like to take a further look into ...,AmazonHelp

In [2]:
amazon_data = pd.read_csv(DATA_PATH)

print("Shape:", amazon_data.shape)

amazon_data.head()

Shape: (168814, 5)

,customer_tweet_id,customer_text,brand_tweet_id,brand_text,brand_name
0,271,@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...,273,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...,AmazonHelp
1,274,@AmazonHelp こちらこそありがとうございました。,275,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...,AmazonHelp
2,272,amazonのfireTVstickが見れない😢,269,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...,AmazonHelp
3,325,amazonプライムビデオ、再生エラーが多いです,324,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...,AmazonHelp
4,616,@AmazonHelp 3 different people have given 3 di...,618,@115820 We'd like to take a further look into ...,AmazonHelp

In [4]:
import pandas as pd
import re

# Make a copy
intent_data = amazon_data.copy()

# Keep only useful columns
intent_data = intent_data[
    ["customer_text", "brand_text"]
].dropna()

# Remove duplicate customer messages
intent_data = intent_data.drop_duplicates(
    subset=["customer_text"]
)

# Basic text cleaning
def clean_text(text):
    text = str(text)
    
    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)
    
    # Remove Twitter mentions
    text = re.sub(r"@\w+", " ", text)
    
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)
    
    return text.strip()


intent_data["customer_text_clean"] = (
    intent_data["customer_text"]
    .apply(clean_text)
)

# Remove extremely short messages
intent_data = intent_data[
    intent_data["customer_text_clean"].str.len() >= 15
]

# Take a reproducible sample for intent discovery
sample_size = min(30_000, len(intent_data))

intent_sample = intent_data.sample(
    n=sample_size,
    random_state=42
).reset_index(drop=True)

print("Original conversations:", len(amazon_data))
print("After cleaning:", len(intent_data))
print("Intent discovery sample:", len(intent_sample))

print("\nSample messages:")
print(intent_sample["customer_text_clean"].head(10).to_string(index=False))

Original conversations: 168814
After cleaning: 147991
Intent discovery sample: 30000

Sample messages:
Contraseña incorrecta y ya la cambié 2 veces, a...
Hi, I’ve received a parcel today, signed for by...
why are so many in stock Prime delivery items s...
Well here we go yet again - PRIME item ordered ...
                   Required Invoice copy of below.
They didn’t advise anything they put me on hold...
latest iOS update on iPad changed orientation t...
x2 Parcels confirmed delivered to Amazon. 1 sel...
                                   Non pas encore.
I bought laptop on 04.10.17 but it’s showing fr...

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import numpy as np

# TF-IDF representation
vectorizer = TfidfVectorizer(
    stop_words="english",
    lowercase=True,
    ngram_range=(1, 2),
    min_df=5,
    max_df=0.90,
    max_features=8000
)

X = vectorizer.fit_transform(
    intent_sample["customer_text_clean"]
)

print("TF-IDF shape:", X.shape)

TF-IDF shape: (30000, 8000)

In [6]:
# Discover initial customer-problem groups

N_CLUSTERS = 12

kmeans = KMeans(
    n_clusters=N_CLUSTERS,
    random_state=42,
    n_init=10
)

intent_sample["cluster"] = kmeans.fit_predict(X)

print("Clusters created:", N_CLUSTERS)
print("\nMessages per cluster:")

print(
    intent_sample["cluster"]
    .value_counts()
    .sort_index()
)

Clusters created: 12

Messages per cluster:
cluster
0       909
1      2203
2       833
3      1965
4      1762
5      1230
6      1495
7      2780
8       929
9      1705
10      912
11    13277
Name: count, dtype: int64

In [7]:
# Show the most important terms in every cluster

terms = np.array(
    vectorizer.get_feature_names_out()
)

order_centroids = (
    kmeans.cluster_centers_
    .argsort()[:, ::-1]
)

for cluster_id in range(N_CLUSTERS):

    top_terms = terms[
        order_centroids[cluster_id, :15]
    ]

    cluster_size = (
        intent_sample["cluster"] == cluster_id
    ).sum()

    print("\n" + "=" * 80)
    print(f"CLUSTER {cluster_id} | Messages: {cluster_size}")
    print("Top terms:", ", ".join(top_terms))

================================================================================
CLUSTER 0 | Messages: 909
Top terms: days, prime, order, days ago, ago, 10 days, delivery, amazon, 10, wait, refund, 15 days, package, 15, time

================================================================================
CLUSTER 1 | Messages: 2203
Top terms: amazon, amazon prime, prime, pay, amazon pay, india, account, package, amazon logistics, logistics, don, amazon india, just, time, balance

================================================================================
CLUSTER 2 | Messages: 833
Top terms: product, product delivered, delivered, received, return, refund, amazon, order, want, got, ordered, deliver, deliver product, time, delivery

================================================================================
CLUSTER 3 | Messages: 1965
Top terms: order, amazon, cancelled, placed, cancel, refund, help, cancel order, received, number, cancelled order, 408, id, order number, order id

================================================================================
CLUSTER 4 | Messages: 1762
Top terms: delivery, date, delivery date, today, amazon, prime, time, package, service, guaranteed, says, guaranteed delivery, delivery service, order, just

================================================================================
CLUSTER 5 | Messages: 1230
Top terms: delivered, package, today, says, delivered today, order, says delivered, package delivered, parcel, delivery, ordered, yesterday, order delivered, item, amazon

================================================================================
CLUSTER 6 | Messages: 1495
Top terms: thanks, just, got, time, ve, amazon, just got, know, want, ordered, refund, package, help, like, thanks help

================================================================================
CLUSTER 7 | Messages: 2780
Top terms: que, la, en, le, el, je, est, pas, et, pour, ai, por, vous, se, lo

================================================================================
CLUSTER 8 | Messages: 929
Top terms: customer, service, customer service, worst, care, customer care, worst customer, amazon, just, amazon customer, help, delivery, time, prime, experience

================================================================================
CLUSTER 9 | Messages: 1705
Top terms: help, email, account, need, sent, received, amazon, need help, ve, got, email address, address, contact, don, password

================================================================================
CLUSTER 10 | Messages: 912
Top terms: day, day delivery, delivery, shipping, day shipping, prime, prime day, days, paid, ordered, order, package, pay, paid day, paying

================================================================================
CLUSTER 11 | Messages: 13277
Top terms: time, prime, yes, ordered, don, ve, app, today, package, ありがとうございます, refund, details, got, guys, thank

In [8]:
# Inspect real customer messages from each cluster

for cluster_id in sorted(intent_sample["cluster"].unique()):

    print("\n" + "=" * 100)
    print(f"CLUSTER {cluster_id}")

    examples = (
        intent_sample[
            intent_sample["cluster"] == cluster_id
        ]["customer_text_clean"]
        .head(5)
    )

    for i, text in enumerate(examples, 1):
        print(f"{i}. {text}")

====================================================================================================
CLUSTER 0
1. Well here we go yet again - PRIME item ordered 11/13 never arrived. Just checked &amp; now it says arriving Wed. So now Prime is 2 days, oh 3, forget it now it can be a week. Sorry to see I can no longer rely on amazon, cannot buy gifts.
2. has ruined my day, ruined my gift, and ruined my mood, because Amazon doesn't know how to count days for shipping, just your cash.
3. Hey my account has been locked for a few days with no reason and now I can't even login to contact support nor place an order.
4. I have already replied to the mail two days back and got no reply. Don't know what investigation is going on at your side.
5. Ur Amazon team till now they didn't refund my payment after 20 days also do solve my issue ✉ __email__ 📱7667342264

====================================================================================================
CLUSTER 1
1. I have ordered canon1300d dslr camera from amazon and they sent me rubbish broken speakers inside the box.
2. Have never experienced such an issue with Amazon. Amazon has infact delivered the products before schedule date. #proudprimemember.
3. Your intention is just passing time.delaying technique.tollally un-professional attitude from Amazon
4. Amazon UK, it's a subscribe &amp; save. Was sent the same day as other items but never arrived.
5. Why is the Indian Amazon Echo skill set limited? Ewelink is not showing up in the skill set!

====================================================================================================
CLUSTER 2
1. I got a product delivered today in a bad shape, not sealed and badly handled. I am not sure the phone is new one or refurbished one. Highly disappointing. Ordered replacement, hope they send a good one.
2. But the rest of the time it is available in my pincode. Why not now. Because of which I can not buy the product.
3. I guess the Lightening deal is just for cheating. Ordered the same product twice and wass canceled by . Not impressed
4. Dirty money game by : Take money, don't deliver the product and refund money after about 2months. Rest assured 😉
5. Highly disappointed with the resolution given rather nothing has been given as per the agent if the product is damaged then I've to bear all

====================================================================================================
CLUSTER 3
1. I place 2 order 4__credit_card__ &amp; 4__credit_card__ I select wrong delivery address by mistake. Fix it
2. How useless is. Apparently my order was undeliverable despite no one having buzzed or called me. No Irn Bru for me 😞
3. Order# 171-2088476-5512354
4. waste of money and poor service even for PRIME customers. order Id 403-8040056-0265138
5. my last two orders had delivery issues. Current order cancelled due to this. Absolutely not expected from Amazon. Frustrating.

====================================================================================================
CLUSTER 4
1. Supposed to be here today (1 a present for tomorrow) tracked it, told it had missed delivery and to advise Amazon if not here by Wednesday!
2. this is the message received from Amazon but there is no contact made with me for delivery
3. I'm confused , are your delivery people really fast? to get my parcel to me today even though it's not dispatched yet 😂😂
4. Make Sure Your Delivery Boys have mPass Swiping Machines Always! It’s becoming a head ache when they don’t have it.
5. Hi! The party is next Saturday &amp; the delivery date is somewhere between 12/5 &amp; 12/8! If all goes well, my sparkly boots should arrive just in time, but I am only a little nervous since they weren’t eligible for Prime! 😬✨ Is the estimated date typically accurate?

====================================================================================================
CLUSTER 5
1. x2 Parcels confirmed delivered to Amazon. 1 seller has received theirs, the other is saying they haven't. Need to track the parcels.. thanks
2. i didnt recvd d parcel but it shows delivered nd i signed d reciept.. i escalated 4 days before still no use..
3. I phoned up last night and you was told no one could find out where my parcels where or guarantee when they would be delivered.
4. Poor delivery service FE not delivered the package at destination
5. RM Tracking shows parcel delivered but postie and me state nothing was posted or received! What is happening? How can this happen? #SoftwareBug #SystemBackDoor #NeverHappenedBefore

====================================================================================================
CLUSTER 6
1. Parcel arrived about 1600 today. Thanks for chasing it up for me
2. Hi there. I wanted to order something from the Sherman Amazon site, but am having trouble as I can't find how to change the wording to English on it. Is there any other way to do this? Thanks
3. Thanks. How quickly will that happen? I've got money burning a hole in my pocket and I don't want to miss the black Friday deals 😁
4. wut? reconfirms order—doh! I guess that's actually what I ordered. thanks, , for the confusing search results! #caveatemptor
5. Once again great service by ..just took 16hours to deliver my #op5t #ontime

====================================================================================================
CLUSTER 7
1. Contraseña incorrecta y ya la cambié 2 veces, aun así me sale lo mismo
2. Des versions qui différent, des conseils qui me font perdre de l'argent, un interlocuteur arrogant et un dédommagement largement inférieur à ce que j'estime
3. Imposible colgar en libro en Llevo desde las ocho y media intentándolo. Imposible, Te ponen más trabas que para visitar al Papa.
4. Je viens de le faire par e-mail &amp; espère une solution rapide. Comment peut-on mettre un noeud sans se rendre compte qu'il y a pas le papier?
5. muy mal vuestro servicio de amazon logistic... que no haya sitio fisico donde recoger me parece lamentable...

====================================================================================================
CLUSTER 8
1. #AmazonIN One of the Poor Customer Support and Fake Promise .... Really Worst Customer Service
2. Thanks Amazon "guaranteed next day" to be told it'll arrive on the 8th. Disgusting treatment by customer service team
3. I have already send a mail to ur customer service
4. it was meant to be here on the 28th, then received and email saying it had been delayed to the 30th then I contacted customer service to be told it will be here today and still no delivery
5. You have excellent customer service that I know but still cannot provide a replacement for a fire TV stick remote? #disappointed

====================================================================================================
CLUSTER 9
1. Hi, I’ve received a parcel today, signed for by a neighbour who I don’t know, the box is like this. Items missing, can you help?
2. They explained there was a 24hr turnaround for the process....not explaining about blocking the russian email etc.....
3. Hey &amp; Reached my max for archiving, need help. Delete somehow? Your phone support in India is horrid, asked same ? 6x.
4. Yes, call and mail but all failed 2 help. How m i supposed to manage 3 days without a phone. Need help. SOS. Such strict policies. help urg
5. Yes.Mr Gaurav help me in the process,but I am unable to log in my Amazon account to post the pics so used this medium..

====================================================================================================
CLUSTER 10
1. why are so many in stock Prime delivery items showing as “get it by Wednesday”. That’s three day delivery not next day delivery.
2. And while we're at out, my wife ordered something, paid for next day (to arrive yesterday) and that did not arrive either. So a lot of unhappy customers in this house right now.
3. I love that now email you AT THE END OF THE DAY that they're delayed in delivering your package for that day.
4. Can please tell me why I've paid £5.99 extra for next day delivery when the parcel hasn't turned up Thanks for screwing up my daughters birthday plans &amp; keeping me waiting till 8pm this evening.!! Extremely pissed off for the record #SORTITOUT #unhappycustomer #fixup
5. Paid for Prime, Amazon’s own Atlanta shipping system is a nightmare and doesn’t even get delivered to me that day even though they left at 9 A.M. I switch allegiance to Best Buy GCU and pay for two years of that, my game isn’t even in my city on release day.

====================================================================================================
CLUSTER 11
1. Required Invoice copy of below.
2. They didn’t advise anything they put me on hold that you cut me off
3. latest iOS update on iPad changed orientation to portrait. Pls fix
4. Non pas encore.
5. I bought laptop on 04.10.17 but it’s showing from 23.08.17 on warranty portal of Lenovo

In [9]:
# Check common support keywords in customer messages

keywords = {
    "delivery": [
        "delivery", "deliver", "delivered", "package",
        "parcel", "shipping", "arrive", "arrived", "late"
    ],
    "refund": [
        "refund", "refunded", "money back", "reimburse"
    ],
    "cancellation": [
        "cancel", "cancelled", "canceled"
    ],
    "payment": [
        "payment", "charged", "charge", "billing",
        "card", "pay", "paid"
    ],
    "account": [
        "account", "login", "locked", "password",
        "sign in", "access"
    ],
    "return": [
        "return", "replacement", "replace"
    ],
    "prime": [
        "prime", "membership", "subscription"
    ],
    "product": [
        "product", "item", "broken", "damaged",
        "wrong item", "defective"
    ]
}

topic_counts = {}

texts = intent_sample["customer_text_clean"].str.lower()

for topic, words in keywords.items():

    pattern = "|".join(
        re.escape(word)
        for word in words
    )

    topic_counts[topic] = texts.str.contains(
        pattern,
        regex=True,
        na=False
    ).sum()

topic_counts_df = (
    pd.DataFrame(
        list(topic_counts.items()),
        columns=["topic", "messages"]
    )
    .sort_values(
        "messages",
        ascending=False
    )
    .reset_index(drop=True)
)

topic_counts_df

          topic  messages
0      delivery      7424
1         prime      2764
2       product      2639
3       payment      2149
4       account      1314
5        refund      1208
6        return      1065
7  cancellation       828

In [10]:
# Inspect real examples for each discovered topic

for topic, words in keywords.items():

    pattern = "|".join(
        re.escape(word)
        for word in words
    )

    mask = intent_sample["customer_text_clean"].str.lower().str.contains(
        pattern,
        regex=True,
        na=False
    )

    examples = (
        intent_sample.loc[
            mask,
            "customer_text_clean"
        ]
        .drop_duplicates()
        .head(10)
    )

    print("\n" + "=" * 100)
    print(f"TOPIC: {topic.upper()}")
    print(f"Matching messages: {mask.sum()}")

    for i, text in enumerate(examples, 1):
        print(f"{i}. {text}")

====================================================================================================
TOPIC: DELIVERY
Matching messages: 7424
1. Hi, I’ve received a parcel today, signed for by a neighbour who I don’t know, the box is like this. Items missing, can you help?
2. why are so many in stock Prime delivery items showing as “get it by Wednesday”. That’s three day delivery not next day delivery.
3. Well here we go yet again - PRIME item ordered 11/13 never arrived. Just checked &amp; now it says arriving Wed. So now Prime is 2 days, oh 3, forget it now it can be a week. Sorry to see I can no longer rely on amazon, cannot buy gifts.
4. latest iOS update on iPad changed orientation to portrait. Pls fix
5. x2 Parcels confirmed delivered to Amazon. 1 seller has received theirs, the other is saying they haven't. Need to track the parcels.. thanks
6. And while we're at out, my wife ordered something, paid for next day (to arrive yesterday) and that did not arrive either. So a lot of unhappy customers in this house right now.
7. cod ww2 comes out tomorrow. My copy still hasn’t dispatched? Can you guarantee it will arrive tomorrow?
8. I place 2 order 4__credit_card__ &amp; 4__credit_card__ I select wrong delivery address by mistake. Fix it
9. Parcel arrived about 1600 today. Thanks for chasing it up for me
10. How useless is. Apparently my order was undeliverable despite no one having buzzed or called me. No Irn Bru for me 😞

====================================================================================================
TOPIC: REFUND
Matching messages: 1208
1. still waiting for a refund...
2. Dirty money game by : Take money, don't deliver the product and refund money after about 2months. Rest assured 😉
3. I placed the order on 27th June. I was told that I will get the cashback 3 months after the purchase. It's Oct and still no cashback refund
4. Ur Amazon team till now they didn't refund my payment after 20 days also do solve my issue ✉ __email__ 📱7667342264
5. IS THIS A JOKE! When I called customer care, they offered me a refund! I DON'T NEED A REFUND! I NEED MY PRODUCT DELIVERED TODAY!!!!!!
6. how would you justify blocking a customer’s number who’s awaiting a refund?
7. I was issued a refund on 17th for a lost trade in and then it dissapered from my account and no one can tell me why and they stopped replying to me misse all black friday deals and ill miss cyber monday as well
8. Refund still not received. 8 months.. How long do i hav to wait? Order no-407-9817231-7613938
9. I can’t even cancel this purchase as it was used under someone else’s account in order to get my money back
10. I've messaged Amazon twice, about a seller who sold me faulty goods who is begging me to leave 5 stars and good feedback in return for a refund. I've had nothing from you apart from a charge for Amazon prime that I am actually unsubscribed from. Well done! Great work

====================================================================================================
TOPIC: CANCELLATION
Matching messages: 828
1. En este momento cancelo la subscripción a Prime. No sirve de nada
2. my last two orders had delivery issues. Current order cancelled due to this. Absolutely not expected from Amazon. Frustrating.
3. I guess the Lightening deal is just for cheating. Ordered the same product twice and wass canceled by . Not impressed
4. I did subscribe 2 the digital that was a 6 mo free but I tried 2 cancel that once I was mad abt an article &amp; it was blank
5. hola! hice una cancelanción de un producto y se genero el cargo a mi tarjeta, pasarón varios días pero no me hacen mi rembolso
6. thats the thing I've been trying to log in to my account but it says it's locked or something so I guess it was cancelled
7. If that’s the case then I would rather cancel my order and buy somewhere else so I don’t get spoilers.
8. I can’t even cancel this purchase as it was used under someone else’s account in order to get my money back
9. Why have you taken a prime payment when I cancelled my subscription??????
10. is not cancelling my product . Even I have tried to cancel this after 5min of ordering. Please do something.

====================================================================================================
TOPIC: PAYMENT
Matching messages: 2149
1. And while we're at out, my wife ordered something, paid for next day (to arrive yesterday) and that did not arrive either. So a lot of unhappy customers in this house right now.
2. I place 2 order 4__credit_card__ &amp; 4__credit_card__ I select wrong delivery address by mistake. Fix it
3. I don't know, as there was no time written on the card. Thanks for the advice, however regardless of what my safe place preferences are, I live on a row of terraces. Neighbours were in...
4. Exchange on LG Q6 pin code is 208007 on 9:40 pm it's working also go to check out page but payment fails again try now showing exch Not acal
5. Can please tell me why I've paid £5.99 extra for next day delivery when the parcel hasn't turned up Thanks for screwing up my daughters birthday plans &amp; keeping me waiting till 8pm this evening.!! Extremely pissed off for the record #SORTITOUT #unhappycustomer #fixup
6. ur A to Z guareentee is worthless. Can't enail u and agents can't understand. #wtf. Do I need to dispute the credit card?
7. Please use this order id 4__credit_card__ to track the issue
8. Paid for Prime, Amazon’s own Atlanta shipping system is a nightmare and doesn’t even get delivered to me that day even though they left at 9 A.M. I switch allegiance to Best Buy GCU and pay for two years of that, my game isn’t even in my city on release day.
9. But hey , it's ok. Not an important package. Not like it's card for my sister's wedding invites. Just leave it wherever.
10. I pay for 2 day shipping to only get my shit the next week Great fucking shit Amazon 😑

====================================================================================================
TOPIC: ACCOUNT
Matching messages: 1314
1. Yes.Mr Gaurav help me in the process,but I am unable to log in my Amazon account to post the pics so used this medium..
2. Thx for the quick response, but I don't want to transfer my account. I want to buy physical goods in the UK + digital books in Spanish
3. Hey my account has been locked for a few days with no reason and now I can't even login to contact support nor place an order.
4. My account clearly lists my “safe place” to leave goods. Why therefore have you ignored that, and delivered the goods to someone living a long way down the street?
5. thats the thing I've been trying to log in to my account but it says it's locked or something so I guess it was cancelled
6. can you add more than one google account to Alexa for calendars?
7. why have you randomly taken £1 from my account? I haven’t purchased anything and I have been notified you have take £1 on 16th November! Why?
8. The account belongs to my father and he don't have tweeter, and we have not got help from your customer care , if u want to cooperate please take this forward.
9. account of __email__ school bag ka return start kiya lekin pick up nahin hua
10. I was issued a refund on 17th for a lost trade in and then it dissapered from my account and no one can tell me why and they stopped replying to me misse all black friday deals and ill miss cyber monday as well

====================================================================================================
TOPIC: RETURN
Matching messages: 1065
1. I got a product delivered today in a bad shape, not sealed and badly handled. I am not sure the phone is new one or refurbished one. Highly disappointing. Ordered replacement, hope they send a good one.
2. why I'm not able to return your faulty item. Why I need to install smartchk app again and again if it does not work.
3. account of __email__ school bag ka return start kiya lekin pick up nahin hua
4. So you're saying we need to sift through broken glass, sort it, buy packaging, and package it separately before returning it to you? Seems a little unreasonable.
5. Got charged 6 times on two different cards today for a replacement order Returned already. 2.5 hrs on phone and no apology.
6. Application is so disgusting that I can't return track from my orders how I can say that order delivered to your location? 2/2
7. I've messaged Amazon twice, about a seller who sold me faulty goods who is begging me to leave 5 stars and good feedback in return for a refund. I've had nothing from you apart from a charge for Amazon prime that I am actually unsubscribed from. Well done! Great work
8. You have excellent customer service that I know but still cannot provide a replacement for a fire TV stick remote? #disappointed
9. horrible customer service Need return of panasonic led tv delivered today. Defective prod. Poor quality perf. (1/2)
10. During the return pickup wrong items were picked by agent, when should i expect the refund?

====================================================================================================
TOPIC: PRIME
Matching messages: 2764
1. why are so many in stock Prime delivery items showing as “get it by Wednesday”. That’s three day delivery not next day delivery.
2. Well here we go yet again - PRIME item ordered 11/13 never arrived. Just checked &amp; now it says arriving Wed. So now Prime is 2 days, oh 3, forget it now it can be a week. Sorry to see I can no longer rely on amazon, cannot buy gifts.
3. waste of money and poor service even for PRIME customers. order Id 403-8040056-0265138
4. En este momento cancelo la subscripción a Prime. No sirve de nada
5. Could you explain why prime deliveries are not always as promised? The T&amp;C saying 'eligible prime orders' is to fool people.
6. Have never experienced such an issue with Amazon. Amazon has infact delivered the products before schedule date. #proudprimemember.
7. Paid for Prime, Amazon’s own Atlanta shipping system is a nightmare and doesn’t even get delivered to me that day even though they left at 9 A.M. I switch allegiance to Best Buy GCU and pay for two years of that, my game isn’t even in my city on release day.
8. How do we stream Prime music on multiple devices at the same time? We have an Echo or Dot in every room of the house, but we can only listen to one song at a time? Not looking to create a music group - need different Prime music in each device. #AmazonPrime
9. This happens 90% of the time we use prime. Last time both myself &amp; partner had both had operations &amp; were house bound. It’s not good enough.
10. Ummmm as an prime member, I’m highly disappointed that my shipping time has been extended😒😒

====================================================================================================
TOPIC: PRODUCT
Matching messages: 2639
1. Hi, I’ve received a parcel today, signed for by a neighbour who I don’t know, the box is like this. Items missing, can you help?
2. why are so many in stock Prime delivery items showing as “get it by Wednesday”. That’s three day delivery not next day delivery.
3. Well here we go yet again - PRIME item ordered 11/13 never arrived. Just checked &amp; now it says arriving Wed. So now Prime is 2 days, oh 3, forget it now it can be a week. Sorry to see I can no longer rely on amazon, cannot buy gifts.
4. I got a product delivered today in a bad shape, not sealed and badly handled. I am not sure the phone is new one or refurbished one. Highly disappointing. Ordered replacement, hope they send a good one.
5. I have ordered canon1300d dslr camera from amazon and they sent me rubbish broken speakers inside the box.
6. But the rest of the time it is available in my pincode. Why not now. Because of which I can not buy the product.
7. I guess the Lightening deal is just for cheating. Ordered the same product twice and wass canceled by . Not impressed
8. Dirty money game by : Take money, don't deliver the product and refund money after about 2months. Rest assured 😉
9. Have never experienced such an issue with Amazon. Amazon has infact delivered the products before schedule date. #proudprimemember.
10. Highly disappointed with the resolution given rather nothing has been given as per the agent if the product is damaged then I've to bear all